# Generated by Django 5.2.6 on 2026-01-28 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting_ships', 'Ожидание размещения кораблей'), ('player1_turn', 'Ход первого игрока'), ('player2_turn', 'Ход второго игрока'), ('finished', 'Игра завершена'), ('cancelled', 'Игра отменена')], default='waiting_ships', max_length=20, verbose_name='Статус игры')),
                ('board_size', models.IntegerField(default=10, help_text='Размер игрового поля (по умолчанию 10x10)', verbose_name='Размер поля')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('current_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Текущий ход')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions_as_player1', to=settings.AUTH_USER_MODEL, verbose_name='Первый игрок')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions_as_player2', to=settings.AUTH_USER_MODEL, verbose_name='Второй игрок')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Сессия игры',
                'verbose_name_plural': 'Сессии игр',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='Строка')),
                ('col', models.IntegerField(verbose_name='Столбец')),
                ('hit', models.BooleanField(verbose_name='Попадание')),
                ('ship_destroyed', models.BooleanField(default=False, verbose_name='Корабль уничтожен')),
                ('ship_size', models.IntegerField(blank=True, null=True, verbose_name='Размер корабля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время хода')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_moves', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='warship.gamesession', verbose_name='Сессия игры')),
            ],
            options={
                'verbose_name': 'Ход игры',
                'verbose_name_plural': 'Ходы игр',
                'ordering': ['created_at'],
                'unique_together': {('game_session', 'player', 'row', 'col')},
            },
        ),
        migrations.CreateModel(
            name='ShipPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ships', models.JSONField(default=list, help_text='Список кораблей в формате [{"size": 4, "cells": [[0,0], [0,1], ...], "destroyed": false}, ...]', verbose_name='Корабли')),
                ('ships_placed', models.BooleanField(default=False, verbose_name='Корабли размещены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_placements', to='warship.gamesession', verbose_name='Сессия игры')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_placements', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Размещение кораблей',
                'verbose_name_plural': 'Размещения кораблей',
                'unique_together': {('game_session', 'player')},
            },
        ),
    ]
