# Generated by Django 5.2.6 on 2026-05-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='is_training',
            field=models.BooleanField(default=False, verbose_name='Тренировка'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('waiting_challenge', 'Ожидание вызова'), ('waiting_ships', 'Ожидание размещения кораблей'), ('player1_turn', 'Ход первого игрока'), ('player2_turn', 'Ход второго игрока'), ('finished', 'Игра завершена'), ('cancelled', 'Игра отменена')], default='waiting_ships', max_length=20, verbose_name='Статус игры'),
        ),
    ]
