# Generated by Django 5.2.6 on 2026-05-24 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playergroup_user_ban_reason_user_banned_at_and_more'),
        ('warship', '0002_gamesession_is_training_alter_gamesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='admin_control_mode',
            field=models.CharField(choices=[('normal', 'Обычный'), ('delayed', 'С задержкой'), ('manual_step', 'Ручной шаг')], default='normal', max_length=20, verbose_name='Режим контроля админом'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_paused',
            field=models.BooleanField(default=False, verbose_name='Пауза'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='last_move_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего хода'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='move_delay_ms',
            field=models.PositiveIntegerField(default=0, verbose_name='Задержка хода (мс)'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='pending_move',
            field=models.JSONField(blank=True, null=True, verbose_name='Ожидающий ход'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player1_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player1_bot', to='core.userbot', verbose_name='Бот первого игрока'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player2_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_player2_bot', to='core.userbot', verbose_name='Бот второго игрока'),
        ),
    ]
